import Head from 'next/head';
import Header from '../../components/Header';
import Nav from '../../components/Nav';
import Results from '../../components/Results';

export default function Movie() {

    return (
        <div className={'ada'}>
            <Head>
                <title>Hulu Clone | Movie</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Nav />
            <Results/>
        </div>
    )
}
